In [1]:
!nvidia-smi

Mon May 12 11:08:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.83                 Driver Version: 572.83         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   53C    P8              4W /   75W |     314MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch

In [4]:
torch.cuda.is_available()

True

In [5]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [6]:
device

'cuda'

In [7]:
torch.cuda.device_count()

1

In [8]:
tensor=torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [9]:
tg=tensor.to(device)
tg.device

device(type='cuda', index=0)

In [10]:
tg.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [22]:
tgc=tg.cpu().numpy

In [24]:
#excercise
f=torch.rand(7,7)

In [26]:
f

tensor([[0.4250, 0.8475, 0.6513, 0.8851, 0.9988, 0.1130, 0.9385],
        [0.5053, 0.8278, 0.2739, 0.2876, 0.5596, 0.9611, 0.3008],
        [0.6153, 0.1223, 0.7419, 0.6352, 0.2352, 0.0922, 0.6522],
        [0.8535, 0.4785, 0.6570, 0.5271, 0.8048, 0.7415, 0.3020],
        [0.6645, 0.8334, 0.5311, 0.9204, 0.7347, 0.0740, 0.6876],
        [0.2949, 0.5953, 0.0977, 0.5037, 0.3649, 0.3244, 0.2550],
        [0.0794, 0.4129, 0.1209, 0.4427, 0.3626, 0.4482, 0.3284]])

In [28]:
f2=torch.rand(1,7)

In [30]:
f2

tensor([[0.4765, 0.9207, 0.0427, 0.4889, 0.8989, 0.9161, 0.2294]])

In [32]:
f2=f2.reshape(7,1)

In [34]:
f2

tensor([[0.4765],
        [0.9207],
        [0.0427],
        [0.4889],
        [0.8989],
        [0.9161],
        [0.2294]])

In [36]:
f2.shape

torch.Size([7, 1])

In [38]:
torch.mm(f,f2)

tensor([[2.6599],
        [2.6077],
        [1.1935],
        [2.6049],
        [2.4425],
        [1.6227],
        [1.4514]])

In [40]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
torch.rand(3,3)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556]])

In [43]:
torch.cuda.manual_seed(1234)

In [45]:
ta=torch.rand(2,3,device="cuda")
tb=torch.rand(2,3,device="cuda")
ta,tb

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [47]:
import torch

# Step 1: Create a random tensor with shape (7, 7)
tensor1 = torch.rand(7, 7)
print("Step 1 - Random tensor (7x7):\n", tensor1)

# Step 2: Perform matrix multiplication with another random tensor (1,7), need to transpose to (7,1) or adjust shape
tensor2 = torch.rand(1, 7)
result2 = torch.matmul(tensor1, tensor2.T)  # (7,7) x (7,1) => (7,1)
print("\nStep 2 - Matrix multiplication result:\n", result2)

# Step 3: Set the random seed to 0 and repeat
torch.manual_seed(0)
tensor1_seed0 = torch.rand(7, 7)
tensor2_seed0 = torch.rand(1, 7)
result3 = torch.matmul(tensor1_seed0, tensor2_seed0.T)
print("\nStep 3 - Random tensor1 with seed 0:\n", tensor1_seed0)
print("\nRandom tensor2 with seed 0:\n", tensor2_seed0)
print("\nMatrix multiplication result with seed 0:\n", result3)

# Step 4: GPU random seed equivalent? YES.
# Use torch.cuda.manual_seed() to seed for CUDA (GPU)
torch.cuda.manual_seed(1234)
print("\nStep 4 - Set GPU random seed to 1234.")

# Step 5: Create two random tensors of shape (2, 3) and send them to GPU
torch.manual_seed(1234)
tensor_a = torch.rand(2, 3, device="cuda")
tensor_b = torch.rand(2, 3, device="cuda")
print("\nStep 5 - Tensor A on GPU:\n", tensor_a)
print("\nTensor B on GPU:\n", tensor_b)

# Step 6: Perform matrix multiplication (requires matching inner dimensions)
# We can transpose tensor_b to (3,2) then multiply
result6 = torch.matmul(tensor_a, tensor_b.T)
print("\nStep 6 - Matrix multiplication result on GPU:\n", result6)

# Step 7: Find max and min values
max_val = torch.max(result6)
min_val = torch.min(result6)
print("\nStep 7 - Max value:", max_val.item())
print("Min value:", min_val.item())

# Step 8: Find max and min indices
max_idx = torch.argmax(result6)
min_idx = torch.argmin(result6)
print("\nStep 8 - Max index:", max_idx.item())
print("Min index:", min_idx.item())

# Step 9: Random tensor with shape (1, 1, 1, 10), remove dimensions of size 1
torch.manual_seed(7)
tensor9 = torch.rand(1, 1, 1, 10)
squeezed_tensor9 = tensor9.squeeze()
print("\nStep 9 - Original tensor:\n", tensor9)
print("Shape of original tensor:", tensor9.shape)
print("\nSqueezed tensor:\n", squeezed_tensor9)
print("Shape of squeezed tensor:", squeezed_tensor9.shape)


Step 1 - Random tensor (7x7):
 tensor([[0.6323, 0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823, 0.6816, 0.9152, 0.3971],
        [0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852, 0.3734],
        [0.3051, 0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081],
        [0.9298, 0.7231, 0.7423, 0.5263, 0.2437, 0.5846, 0.0332],
        [0.1387, 0.2422, 0.8155, 0.7932, 0.2783, 0.4820, 0.8198],
        [0.9971, 0.6984, 0.5675, 0.8352, 0.2056, 0.5932, 0.1123]])

Step 2 - Matrix multiplication result:
 tensor([[1.1161],
        [1.6576],
        [1.7222],
        [0.8016],
        [1.6815],
        [2.2335],
        [1.8347]])

Step 3 - Random tensor1 with seed 0:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.